version: "3.9"

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  pghero:
    image: ankane/pghero
    ports:
      - "8010:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db


  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  redis:
    image: "redis:alpine"
    restart: always
    volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf # feel free to omit this line if you want to stick with the default config
        - "redis:/data"
    ports:
      - "6379:6379"

volumes:
    db-data:
    pgadmin-data:
    redis: {}